# Generated by Django 4.1.3 on 2022-11-26 15:56

from django.db import migrations, models
import django.db.models.deletion
import touristresource.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouristResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Recurso Turístico',
                'verbose_name_plural': 'Recursos Turísticos',
            },
        ),
        migrations.CreateModel(
            name='TouristResourceImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
                ('image', models.ImageField(upload_to=touristresource.models.renameFile, verbose_name='Logotipo')),
                ('idTouristResource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touristresource.touristresource', verbose_name='Recurso Turísticos')),
            ],
            options={
                'verbose_name': 'Imagen del Recurso Turístico',
                'verbose_name_plural': 'Imagenes del Recursos Turísticos',
            },
        ),
    ]
