# Generated by Django 4.1.3 on 2023-06-05 04:14

from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion
import touristresource.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0005_alter_language_options_rename_flags_language_flag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureAccess',
            fields=[
                ('idIA', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30, verbose_name='Nombre')),
                ('name_es', models.CharField(default='', max_length=30, null=True, verbose_name='Nombre')),
                ('name_en', models.CharField(default='', max_length=30, null=True, verbose_name='Nombre')),
                ('name_ru', models.CharField(default='', max_length=30, null=True, verbose_name='Nombre')),
                ('name_fr', models.CharField(default='', max_length=30, null=True, verbose_name='Nombre')),
                ('slug', models.CharField(max_length=30, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Infraestructura de acceso',
                'verbose_name_plural': 'Infraestructuras de accesos',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='InfrastructureAccessResourceTourist',
            fields=[
                ('idIART', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Infraestructura de acceso del recurso turístico',
                'verbose_name_plural': 'Infraestructuras de accesos del recurso turístico',
                'ordering': ('idResourceTourist', 'idInfrastructureAccess'),
            },
        ),
        migrations.CreateModel(
            name='MediaResourceTourist',
            fields=[
                ('idMediaRT', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Media del Recurso Turístico',
                'verbose_name_plural': 'Medias de los Recursos Turísticos',
            },
        ),
        migrations.CreateModel(
            name='ResourceTourist',
            fields=[
                ('idRT', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30, verbose_name='Nombre')),
                ('name_es', models.CharField(default='', max_length=30, null=True, verbose_name='Nombre')),
                ('name_en', models.CharField(default='', max_length=30, null=True, verbose_name='Nombre')),
                ('name_ru', models.CharField(default='', max_length=30, null=True, verbose_name='Nombre')),
                ('name_fr', models.CharField(default='', max_length=30, null=True, verbose_name='Nombre')),
                ('slug', models.CharField(max_length=30, unique=True, verbose_name='slug')),
                ('description', models.TextField(max_length=10000, verbose_name='Descripción')),
                ('description_es', models.TextField(max_length=10000, null=True, verbose_name='Descripción')),
                ('description_en', models.TextField(max_length=10000, null=True, verbose_name='Descripción')),
                ('description_ru', models.TextField(max_length=10000, null=True, verbose_name='Descripción')),
                ('description_fr', models.TextField(max_length=10000, null=True, verbose_name='Descripción')),
                ('address', models.TextField(max_length=10000, verbose_name='Dirección')),
                ('address_es', models.TextField(max_length=10000, null=True, verbose_name='Dirección')),
                ('address_en', models.TextField(max_length=10000, null=True, verbose_name='Dirección')),
                ('address_ru', models.TextField(max_length=10000, null=True, verbose_name='Dirección')),
                ('address_fr', models.TextField(max_length=10000, null=True, verbose_name='Dirección')),
                ('comments', models.TextField(blank=True, default='', max_length=10000, verbose_name='Otros comentarios')),
                ('comments_es', models.TextField(blank=True, default='', max_length=10000, null=True, verbose_name='Otros comentarios')),
                ('comments_en', models.TextField(blank=True, default='', max_length=10000, null=True, verbose_name='Otros comentarios')),
                ('comments_ru', models.TextField(blank=True, default='', max_length=10000, null=True, verbose_name='Otros comentarios')),
                ('comments_fr', models.TextField(blank=True, default='', max_length=10000, null=True, verbose_name='Otros comentarios')),
                ('geoLocLat', models.DecimalField(decimal_places=8, default=0.0, max_digits=15, verbose_name='Latitud')),
                ('geoLocLon', models.DecimalField(decimal_places=8, default=0.0, max_digits=15, verbose_name='Longitud')),
            ],
            options={
                'verbose_name': 'Recurso turístico',
                'verbose_name_plural': 'Recursos turísticos',
            },
        ),
        migrations.CreateModel(
            name='ResourceTouristCloset',
            fields=[
                ('idResourceTouristCloset', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Recurso Turístico cercano',
                'verbose_name_plural': 'Recursos Turísticos cercanos',
                'ordering': ('idResourceTouristCloset', 'idRTSource', 'idRTTo'),
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('idSchedule', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('name_es', models.CharField(max_length=50, null=True, verbose_name='Nombre')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Nombre')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Nombre')),
                ('name_fr', models.CharField(max_length=50, null=True, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('startTime', models.TimeField(verbose_name='Hora de inicio')),
                ('endTime', models.TimeField(verbose_name='Hora de terminacion')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ('startTime', 'endTime', 'name'),
            },
        ),
        migrations.CreateModel(
            name='TourismType',
            fields=[
                ('idTT', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30, verbose_name='Nombre')),
                ('name_es', models.CharField(default='', max_length=30, null=True, verbose_name='Nombre')),
                ('name_en', models.CharField(default='', max_length=30, null=True, verbose_name='Nombre')),
                ('name_ru', models.CharField(default='', max_length=30, null=True, verbose_name='Nombre')),
                ('name_fr', models.CharField(default='', max_length=30, null=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='Descripción')),
                ('description_es', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
                ('description_en', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
                ('description_ru', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
                ('description_fr', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
                ('slug', models.CharField(max_length=30, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Modalidad de Turismo',
                'verbose_name_plural': 'Modalidades de Turismo',
                'ordering': ('name', 'description'),
            },
        ),
        migrations.CreateModel(
            name='TouristAttraction',
            fields=[
                ('idTA', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30, verbose_name='Nombre')),
                ('name_es', models.CharField(default='', max_length=30, null=True, verbose_name='Nombre')),
                ('name_en', models.CharField(default='', max_length=30, null=True, verbose_name='Nombre')),
                ('name_ru', models.CharField(default='', max_length=30, null=True, verbose_name='Nombre')),
                ('name_fr', models.CharField(default='', max_length=30, null=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='Descripción')),
                ('description_es', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
                ('description_en', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
                ('description_ru', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
                ('description_fr', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
                ('slug', models.CharField(max_length=30, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Atractivo turístico',
                'verbose_name_plural': 'Atractivos turísticos',
                'ordering': ('name', 'description'),
            },
        ),
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('idTS', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30, verbose_name='Nombre')),
                ('name_es', models.CharField(default='', max_length=30, null=True, verbose_name='Nombre')),
                ('name_en', models.CharField(default='', max_length=30, null=True, verbose_name='Nombre')),
                ('name_ru', models.CharField(default='', max_length=30, null=True, verbose_name='Nombre')),
                ('name_fr', models.CharField(default='', max_length=30, null=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='Descripción')),
                ('description_es', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
                ('description_en', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
                ('description_ru', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
                ('description_fr', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
                ('slug', models.CharField(max_length=30, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Tipo de servicio',
                'verbose_name_plural': 'Tipos de servicios',
                'ordering': ('name', 'description'),
            },
        ),
        migrations.CreateModel(
            name='MediaImageRT',
            fields=[
                ('mediaresourcetourist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='touristresource.mediaresourcetourist')),
                ('image', models.ImageField(upload_to=touristresource.models.renameFile, verbose_name='Imagen del recurso')),
            ],
            options={
                'verbose_name': 'Imagen del Recurso Turístico',
                'verbose_name_plural': 'Imágenes del Recurso Turístico',
            },
            bases=('touristresource.mediaresourcetourist',),
        ),
        migrations.CreateModel(
            name='TouristAttractionResourceTourist',
            fields=[
                ('idTART', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idResourceTourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='touristresource.resourcetourist', verbose_name='Recurso turístico')),
                ('idTouristAttraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touristresource.touristattraction', verbose_name='Atractivo turístico')),
            ],
            options={
                'verbose_name': 'Atractivo del recurso turístico',
                'verbose_name_plural': 'Atractivos del recurso turístico',
                'ordering': ('idResourceTourist', 'idTouristAttraction'),
            },
        ),
        migrations.CreateModel(
            name='TourismTypeResourceTourist',
            fields=[
                ('idTTRT', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idResourceTourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_tourism', to='touristresource.resourcetourist', verbose_name='Recurso turístico')),
                ('idTourismType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touristresource.tourismtype', verbose_name='Tipo de turismo')),
            ],
            options={
                'verbose_name': 'Modalidad de turismo del recurso turístico',
                'verbose_name_plural': 'Modalidades de turismo del recurso turístico',
                'ordering': ('idResourceTourist', 'idTourismType'),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('idService', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idResourceTourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='touristresource.resourcetourist', verbose_name='Recurso turístico')),
                ('idSchedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='touristresource.schedule', verbose_name='Horario del servicio')),
                ('idTypeService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_service', to='touristresource.typeservice', verbose_name='Tipo de servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ('idResourceTourist', 'idTypeService', 'idSchedule'),
            },
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('startTime', 'endTime'), name='unique_range_time'),
        ),
        migrations.AddField(
            model_name='resourcetouristcloset',
            name='idRTSource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_rt_source', to='touristresource.resourcetourist', verbose_name='Recurso Turístico origen'),
        ),
        migrations.AddField(
            model_name='resourcetouristcloset',
            name='idRTTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_rt_to', to='touristresource.resourcetourist', verbose_name='Recurso Turistico destino'),
        ),
        migrations.AddField(
            model_name='resourcetourist',
            name='idMunicipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resourcetourists', to='country.municipality', verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='mediaresourcetourist',
            name='idResourceTourist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='touristresource.resourcetourist', verbose_name='Recurso turístico'),
        ),
        migrations.AddField(
            model_name='infrastructureaccessresourcetourist',
            name='idInfrastructureAccess',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touristresource.infrastructureaccess', verbose_name='Infraestructura de acceso'),
        ),
        migrations.AddField(
            model_name='infrastructureaccessresourcetourist',
            name='idResourceTourist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure_access', to='touristresource.resourcetourist', verbose_name='Recurso turístico'),
        ),
        migrations.AddConstraint(
            model_name='touristattractionresourcetourist',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('idResourceTourist', 'idTouristAttraction'), name='unique_attraction'),
        ),
        migrations.AddConstraint(
            model_name='tourismtyperesourcetourist',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('idResourceTourist', 'idTourismType'), name='unique_tourismtype'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('idResourceTourist', 'idTypeService', 'idSchedule'), name='unique_service'),
        ),
        migrations.AddConstraint(
            model_name='resourcetouristcloset',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('idRTSource', 'idRTTo'), name='unique_resource_tourist_closet'),
        ),
        migrations.AddConstraint(
            model_name='infrastructureaccessresourcetourist',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('idResourceTourist', 'idInfrastructureAccess'), name='unique_infrastructure_access_tourist'),
        ),
    ]
