# Generated by Django 4.1.3 on 2022-12-30 04:36

from django.db import migrations, models
import django.db.models.constraints
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceTourist',
            fields=[
                ('idRT', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Recurso turístico',
                'verbose_name_plural': 'Recursos turísticos',
            },
        ),
        migrations.CreateModel(
            name='ScheduleService',
            fields=[
                ('idScheduleClass', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('startTime', models.TimeField(verbose_name='Hora de inicio')),
                ('endTime', models.TimeField(verbose_name='Hora de terminacion')),
            ],
            options={
                'verbose_name': 'Horario de servicio',
                'verbose_name_plural': 'Horarios de servicio',
                'ordering': ('startTime', 'endTime', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='TourismType',
            fields=[
                ('idTT', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(default='', max_length=30, verbose_name='Tipo de turismo')),
                ('type_es', models.CharField(default='', max_length=30, null=True, verbose_name='Tipo de turismo')),
                ('type_en', models.CharField(default='', max_length=30, null=True, verbose_name='Tipo de turismo')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='Descripción')),
                ('description_es', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
                ('description_en', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
                ('slug', models.CharField(max_length=30, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Tipo de turismo',
                'verbose_name_plural': 'Tipos de turismo',
                'ordering': ('type', 'description'),
            },
        ),
        migrations.CreateModel(
            name='TouristResourceImage',
            fields=[
                ('idTRI', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Imagen del recurso turístico',
                'verbose_name_plural': 'Imagenes del recurso turístico',
            },
        ),
        migrations.CreateModel(
            name='TouristResourceVideo',
            fields=[
                ('idTRV', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Video del recurso turístico',
                'verbose_name_plural': 'Videos del recurso turístico',
            },
        ),
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('idTS', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(default='', max_length=30, verbose_name='Tipo de servicio')),
                ('type_es', models.CharField(default='', max_length=30, null=True, verbose_name='Tipo de servicio')),
                ('type_en', models.CharField(default='', max_length=30, null=True, verbose_name='Tipo de servicio')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='Descripción')),
                ('description_es', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
                ('description_en', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
                ('slug', models.CharField(max_length=30, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Tipo de servicio',
                'verbose_name_plural': 'Tipos de servicios',
                'ordering': ('type', 'description'),
            },
        ),
        migrations.CreateModel(
            name='ValueTouristic',
            fields=[
                ('idVT', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=40, verbose_name='Valor')),
                ('value_es', models.CharField(default='', max_length=40, null=True, verbose_name='Valor')),
                ('value_en', models.CharField(default='', max_length=40, null=True, verbose_name='Valor')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='Descripción')),
                ('description_es', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
                ('description_en', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Descripción')),
                ('slug', models.SlugField(max_length=40, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Valor turístico',
                'verbose_name_plural': 'Valores turísticos',
                'ordering': ('value', 'description'),
            },
        ),
        migrations.AddConstraint(
            model_name='scheduleservice',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('startTime', 'endTime'), name='unique_range_time'),
        ),
    ]
