# Generated by Django 4.1.3 on 2023-05-26 15:00

from django.db import migrations, models
import django.db.models.constraints
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('touristresource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('idSchedule', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('name_es', models.CharField(max_length=50, null=True, verbose_name='Nombre')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Nombre')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Nombre')),
                ('name_fr', models.CharField(max_length=50, null=True, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('startTime', models.TimeField(verbose_name='Hora de inicio')),
                ('endTime', models.TimeField(verbose_name='Hora de terminacion')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ('startTime', 'endTime', 'name'),
            },
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('startTime', 'endTime'), name='unique_range_time'),
        ),
    ]
