# Generated by Django 4.1.3 on 2023-06-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristresource', '0002_alter_resourcetourist_geoloclat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismtype',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tourismtype',
            name='name_en',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tourismtype',
            name='name_es',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tourismtype',
            name='name_fr',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tourismtype',
            name='name_ru',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
