# Generated by Django 4.1.3 on 2022-11-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristresource', '0002_alter_touristresource_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristresource',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='touristresourceimage',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='touristresourceimage',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
