# Generated by Django 4.1.3 on 2023-05-26 20:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('touristresource', '0002_schedule_schedule_unique_range_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureAccess',
            fields=[
                ('idIA', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30, verbose_name='Nombre')),
                ('name_es', models.CharField(default='', max_length=30, null=True, verbose_name='Nombre')),
                ('name_en', models.CharField(default='', max_length=30, null=True, verbose_name='Nombre')),
                ('name_ru', models.CharField(default='', max_length=30, null=True, verbose_name='Nombre')),
                ('name_fr', models.CharField(default='', max_length=30, null=True, verbose_name='Nombre')),
                ('slug', models.CharField(max_length=30, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Infraestructura de acceso',
                'verbose_name_plural': 'Infraestructuras de accesos',
                'ordering': ('name',),
            },
        ),
    ]
