# Generated by Django 4.1.3 on 2023-06-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristresource', '0003_alter_tourismtype_name_alter_tourismtype_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcetourist',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='resourcetourist',
            name='name_en',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='resourcetourist',
            name='name_es',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='resourcetourist',
            name='name_fr',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='resourcetourist',
            name='name_ru',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='resourcetourist',
            name='slug',
            field=models.CharField(max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='tourismtype',
            name='slug',
            field=models.CharField(max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
