# Generated by Django 4.1.3 on 2022-11-28 20:49

from django.db import migrations, models
import touristresource.models


class Migration(migrations.Migration):

    dependencies = [
        ('touristresource', '0003_alter_touristresource_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristresourceimage',
            name='image',
            field=models.ImageField(upload_to=touristresource.models.renameFile, verbose_name='Imagen del recurso'),
        ),
    ]
