# Generated by Django 4.1.3 on 2022-12-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristresource', '0004_alter_touristresourceimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristresource',
            name='description',
            field=models.TextField(max_length=10000, verbose_name='Descripción'),
        ),
    ]
