# Generated by Django 4.1.3 on 2023-05-26 21:11

from django.db import migrations, models
import django.db.models.deletion
import touristresource.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('touristresource', '0004_resourcetourist_tourismtyperesourcetourist_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaResourceTourist',
            fields=[
                ('idMediaRT', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idResourceTourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touristresource.resourcetourist', verbose_name='Recurso turístico')),
            ],
            options={
                'verbose_name': 'Media del Recurso Turístico',
                'verbose_name_plural': 'Medias de los Recursos Turísticos',
            },
        ),
        migrations.CreateModel(
            name='MediaImageRT',
            fields=[
                ('mediaresourcetourist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='touristresource.mediaresourcetourist')),
                ('image', models.ImageField(upload_to=touristresource.models.renameFile, verbose_name='Imagen del recurso')),
            ],
            bases=('touristresource.mediaresourcetourist',),
        ),
    ]
