# Generated by Django 4.1.3 on 2023-05-29 12:16

from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
        ('touristresource', '0005_mediaresourcetourist_mediaimagert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaimagert',
            options={'verbose_name': 'Imagen del Recurso Turístico', 'verbose_name_plural': 'Imágenes de los Recursos Turísticos'},
        ),
        migrations.AddField(
            model_name='resourcetourist',
            name='comments',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Otros comentarios'),
        ),
        migrations.AddField(
            model_name='resourcetourist',
            name='description',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='resourcetourist',
            name='idMunicipality',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='resourcetourists', to='country.municipality', verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='resourcetourist',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='resourcetourist',
            name='slug',
            field=models.CharField(default=None, max_length=30, unique=True, verbose_name='slug'),
        ),
        migrations.CreateModel(
            name='ResourceTouristCloset',
            fields=[
                ('idResourceTouristCloset', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idRTSource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_rt_source', to='touristresource.resourcetourist', verbose_name='Recurso Turístico origen')),
                ('idRTTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_rt_to', to='touristresource.resourcetourist', verbose_name='Recurso Turistico destino')),
            ],
            options={
                'verbose_name': 'Recurso Turístico cercano',
                'verbose_name_plural': 'Recursos Turísticos cercanos',
                'ordering': ('idResourceTouristCloset', 'idRTSource', 'idRTTo'),
            },
        ),
        migrations.AddConstraint(
            model_name='resourcetouristcloset',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('idRTSource', 'idRTTo'), name='unique_resource_tourist_closet'),
        ),
    ]
