# Generated by Django 4.1.3 on 2022-12-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristresource', '0006_tourismtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourismtype',
            name='name',
        ),
        migrations.AddField(
            model_name='tourismtype',
            name='type',
            field=models.CharField(default='', max_length=30, verbose_name='Tipo de turismo'),
        ),
    ]
