# Generated by Django 4.1.3 on 2023-05-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristresource', '0006_alter_mediaimagert_options_resourcetourist_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcetourist',
            name='slug',
            field=models.CharField(max_length=30, unique=True, verbose_name='slug'),
        ),
    ]
