# Generated by Django 4.1.3 on 2022-12-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristresource', '0007_remove_tourismtype_name_tourismtype_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourismtype',
            name='description_en',
            field=models.TextField(max_length=10000, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='tourismtype',
            name='description_es',
            field=models.TextField(max_length=10000, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='tourismtype',
            name='type_en',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='Tipo de turismo'),
        ),
        migrations.AddField(
            model_name='tourismtype',
            name='type_es',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='Tipo de turismo'),
        ),
    ]
