# Generated by Django 4.1.3 on 2023-05-29 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
        ('touristresource', '0007_alter_resourcetourist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcetourist',
            name='idMunicipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resourcetourists', to='country.municipality', verbose_name='Municipio'),
        ),
    ]
