# Generated by Django 4.1.3 on 2022-12-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristresource', '0008_tourismtype_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourismtype',
            name='slug',
            field=models.CharField(default='', max_length=30, verbose_name='slug'),
        ),
    ]
