# Generated by Django 4.1.3 on 2023-05-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristresource', '0009_resourcetourist_comments_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetourist',
            name='address',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='resourcetourist',
            name='address_en',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='resourcetourist',
            name='address_es',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='resourcetourist',
            name='address_fr',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='resourcetourist',
            name='address_ru',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='resourcetourist',
            name='geoLocLat',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=15, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='resourcetourist',
            name='geoLocLon',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=15, verbose_name='Longitud'),
        ),
    ]
