# Generated by Django 4.1.3 on 2022-12-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristresource', '0009_tourismtype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismtype',
            name='slug',
            field=models.CharField(max_length=30, unique=True, verbose_name='slug'),
        ),
    ]
