# Generated by Django 4.1.3 on 2022-12-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristresource', '0010_alter_tourismtype_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourismtype',
            options={'ordering': ('type',), 'verbose_name': 'Tipo de Turismo', 'verbose_name_plural': 'Tipos de Turismo'},
        ),
        migrations.AlterField(
            model_name='tourismtype',
            name='description',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tourismtype',
            name='description_en',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tourismtype',
            name='description_es',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Descripción'),
        ),
    ]
