# Generated by Django 4.1.3 on 2023-06-01 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touristresource', '0010_resourcetourist_address_resourcetourist_address_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaimagert',
            options={'verbose_name': 'Imagen del Recurso Turístico', 'verbose_name_plural': 'Imágenes del Recurso Turístico'},
        ),
    ]
