# Generated by Django 4.1.3 on 2023-06-02 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touristresource', '0011_alter_mediaimagert_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='idResourceTourist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='touristresource.resourcetourist', verbose_name='Recurso turístico'),
        ),
    ]
