# Generated by Django 4.1.3 on 2023-06-02 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touristresource', '0012_alter_service_idresourcetourist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcetourist',
            name='address',
            field=models.TextField(default='', max_length=10000, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='resourcetourist',
            name='address_en',
            field=models.TextField(default='', max_length=10000, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='resourcetourist',
            name='address_es',
            field=models.TextField(default='', max_length=10000, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='resourcetourist',
            name='address_fr',
            field=models.TextField(default='', max_length=10000, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='resourcetourist',
            name='address_ru',
            field=models.TextField(default='', max_length=10000, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='resourcetourist',
            name='comments',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='Otros comentarios'),
        ),
        migrations.AlterField(
            model_name='resourcetourist',
            name='comments_en',
            field=models.TextField(blank=True, default='', max_length=10000, null=True, verbose_name='Otros comentarios'),
        ),
        migrations.AlterField(
            model_name='resourcetourist',
            name='comments_es',
            field=models.TextField(blank=True, default='', max_length=10000, null=True, verbose_name='Otros comentarios'),
        ),
        migrations.AlterField(
            model_name='resourcetourist',
            name='comments_fr',
            field=models.TextField(blank=True, default='', max_length=10000, null=True, verbose_name='Otros comentarios'),
        ),
        migrations.AlterField(
            model_name='resourcetourist',
            name='comments_ru',
            field=models.TextField(blank=True, default='', max_length=10000, null=True, verbose_name='Otros comentarios'),
        ),
        migrations.AlterField(
            model_name='resourcetourist',
            name='description',
            field=models.TextField(default='', max_length=10000, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='resourcetourist',
            name='description_en',
            field=models.TextField(default='', max_length=10000, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='resourcetourist',
            name='description_es',
            field=models.TextField(default='', max_length=10000, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='resourcetourist',
            name='description_fr',
            field=models.TextField(default='', max_length=10000, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='resourcetourist',
            name='description_ru',
            field=models.TextField(default='', max_length=10000, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='service',
            name='idSchedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='touristresource.schedule', verbose_name='Horario del servicio'),
        ),
        migrations.AlterField(
            model_name='service',
            name='idTypeService',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_service', to='touristresource.typeservice', verbose_name='Tipo de servicio'),
        ),
    ]
