# Generated by Django 4.1.3 on 2023-06-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristresource', '0013_alter_resourcetourist_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcetourist',
            name='address',
            field=models.TextField(max_length=10000, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='resourcetourist',
            name='address_en',
            field=models.TextField(max_length=10000, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='resourcetourist',
            name='address_es',
            field=models.TextField(max_length=10000, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='resourcetourist',
            name='address_fr',
            field=models.TextField(max_length=10000, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='resourcetourist',
            name='address_ru',
            field=models.TextField(max_length=10000, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='resourcetourist',
            name='description',
            field=models.TextField(max_length=10000, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='resourcetourist',
            name='description_en',
            field=models.TextField(max_length=10000, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='resourcetourist',
            name='description_es',
            field=models.TextField(max_length=10000, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='resourcetourist',
            name='description_fr',
            field=models.TextField(max_length=10000, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='resourcetourist',
            name='description_ru',
            field=models.TextField(max_length=10000, null=True, verbose_name='Descripción'),
        ),
    ]
