# Generated by Django 4.1.3 on 2023-05-26 14:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('idProvince', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50, verbose_name='Nombre')),
                ('name_es', models.CharField(default='', max_length=50, null=True, verbose_name='Nombre')),
                ('name_en', models.CharField(default='', max_length=50, null=True, verbose_name='Nombre')),
                ('name_ru', models.CharField(default='', max_length=50, null=True, verbose_name='Nombre')),
                ('name_fr', models.CharField(default='', max_length=50, null=True, verbose_name='Nombre')),
                ('slug', models.CharField(max_length=50, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('idMunicipality', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50, verbose_name='Nombre')),
                ('name_es', models.CharField(default='', max_length=50, null=True, verbose_name='Nombre')),
                ('name_en', models.CharField(default='', max_length=50, null=True, verbose_name='Nombre')),
                ('name_ru', models.CharField(default='', max_length=50, null=True, verbose_name='Nombre')),
                ('name_fr', models.CharField(default='', max_length=50, null=True, verbose_name='Nombre')),
                ('slug', models.CharField(max_length=50, unique=True, verbose_name='slug')),
                ('idProvince', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalitys', to='country.province', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
    ]
