# Generated by Django 4.1.3 on 2023-06-01 20:58

import country.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('idCountry', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50, verbose_name='Nombre')),
                ('name_es', models.CharField(default='', max_length=50, null=True, verbose_name='Nombre')),
                ('name_en', models.CharField(default='', max_length=50, null=True, verbose_name='Nombre')),
                ('name_ru', models.CharField(default='', max_length=50, null=True, verbose_name='Nombre')),
                ('name_fr', models.CharField(default='', max_length=50, null=True, verbose_name='Nombre')),
                ('ISO639v1', models.CharField(max_length=50, unique=True, verbose_name='ISO 639-1')),
                ('flags', models.ImageField(upload_to=country.models.renameFile, verbose_name='Bandera')),
            ],
        ),
    ]
