# Generated by Django 4.1.3 on 2023-06-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='slug',
            field=models.CharField(default='w', max_length=50, unique=True, verbose_name='slug'),
        ),
    ]
