# Generated by Django 4.1.3 on 2023-06-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_language_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=models.CharField(max_length=50, unique=True, verbose_name='slug'),
        ),
    ]
