# Generated by Django 4.1.3 on 2023-06-01 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_alter_language_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Idioma', 'verbose_name_plural': 'Idiomas'},
        ),
        migrations.RenameField(
            model_name='language',
            old_name='flags',
            new_name='flag',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='idCountry',
            new_name='idLanguage',
        ),
    ]
