# Generated by Django 4.0 on 2022-11-12 15:19

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accescontrol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='userdrpa',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='userdrpa',
            name='numberMobile',
            field=models.CharField(blank=True, default='', max_length=11, validators=[django.core.validators.RegexValidator('^\\d+$', 'Los campos de números de teléfono y móvil admite solamente dígitos')], verbose_name='Número del móvil'),
        ),
        migrations.AlterField(
            model_name='userdrpa',
            name='numberPhone',
            field=models.CharField(blank=True, default='', max_length=11, validators=[django.core.validators.RegexValidator('^\\d+$', 'Los campos de números de teléfono y móvil admite solamente dígitos')], verbose_name='Número de teléfono'),
        ),
    ]
