# Generated by Django 4.1.3 on 2022-11-26 15:56

import accescontrol.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accescontrol', '0002_role_alter_userdrpa_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userdrpa',
            managers=[
                ('objects', accescontrol.models.UserDRPAManager()),
            ],
        ),
        migrations.AlterField(
            model_name='userdrpa',
            name='typeAccount',
            field=models.CharField(choices=[('manual', 'Cuenta manual'), ('ldap', 'Cuenta ldap')], default='manual', max_length=6, verbose_name='Tipo de cuenta'),
        ),
    ]
