# Generated by Django 4.1.3 on 2022-12-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accescontrol', '0003_alter_userdrpa_managers_alter_userdrpa_typeaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdrpa',
            name='typeAccount',
        ),
    ]
