# Generated by Django 4.1.3 on 2022-12-24 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accescontrol', '0004_remove_userdrpa_typeaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdrpa',
            old_name='logo',
            new_name='avatar',
        ),
    ]
